/* Auth */
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

/* Portfolio */
export const SELECT_PORTFOLIO = 'SELECT_PORTFOLIO';
export const GET_SELECTED_PORTFOLIO = 'GET_SELECTED_PORTFOLIO';
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const PORTFOLIO_LOAD_ERROR = 'PORTFOLIO_LOAD_ERROR';
export const PORTFOLIO_CREATE_ERROR = 'PORTFOLIO_CREATE_ERROR';
export const PORTFOLIO_EDIT_ERROR = 'PORTFOLIO_EDIT_ERROR';
export const PORTFOLIO_DELETE_ERROR = 'PORTFOLIO_DELETE_ERROR';
export const EMPTY_PORTFOLIO = 'EMPTY_PORTFOLIO';

/* USER */
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const AVATAR_ERROR = 'AVATAR_ERROR';
export const UPDATE_USER = 'UPDATE_USER';
export const FAIL_UPDATE_USER = 'FAIL_UPDATE_USER';

/* ALERT */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/* STOCK */
export const RESET_STOCK_LOADING = 'RESET_STOCK_LOADING';
export const GET_STOCK_LIST = 'GET_STOCK_LIST';
export const GET_EMPTY_STOCK_LIST = 'GET_EMPTY_STOCK_LIST';
export const GET_STOCK_ERROR = 'GET_STOCK_ERROR';
export const GET_STOCK_GROUP = 'GET_STOCK_GROUP';
export const GET_STOCK_GROUP_ERROR = 'GET_STOCK_GROUP_ERROR';
export const ADD_STOCK = 'ADD_STOCK';
export const EDIT_STOCK = 'EDIT_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const CHECK_MARKET_STATUS = 'CHECK_MARKET_STATUS';
export const CHECK_MARKET_STATUS_ERROR = 'CHECK_MARKET_STATUS_ERROR';
export const EDIT_DAILY_RETURN = 'EDIT_DAILY_RETURN';
export const EDIT_OVERALL_RETURN = 'EDIT_OVERALL_RETURN';
export const GET_SECTOR = 'GET_SECTOR';
export const GET_SECTOR_ERROR = 'GET_SECTOR_ERROR';
export const CLOSE_POSITION = 'CLOSE_POSITION';
export const CLOSE_POSITION_ERROR = 'CLOSE_POSITION_ERROR';

/* CASH */
export const GET_CASH_LIST = 'GET_CASH_LIST';
export const GET_TOTAL_CASH = 'GET_TOTAL_CASH';
export const GET_CASH_ERROR = 'GET_CASH_ERROR';
export const ADD_CASH = 'ADD_CASH';
export const ADD_CASH_ERROR = 'ADD_CASH_ERROR';


