/* Auth */
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

/* Portfolio */
export const SELECT_PORTFOLIO = 'SELECT_PORTFOLIO';
export const LOAD_PORTFOLIO = 'LOAD_PORTFOLIO';
export const CREATE_PORTFOLIO = 'CREATE_PORTFOLIO';
export const EDIT_PORTFOLIO = 'EDIT_PORTFOLIO';
export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO';
export const PORTFOLIO_LOAD_ERROR = 'PORTFOLIO_LOAD_ERROR';
export const PORTFOLIO_EDIT_ERROR = 'PORTFOLIO_EDIT_ERROR';
export const PORTFOLIO_DELETE_ERROR = 'PORTFOLIO_DELETE_ERROR';
export const EMPTY_PORTFOLIO = 'EMPTY_PORTFOLIO';